name: Deploy and Release on Tag Push

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  deploy_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package the project
        run: zip -r DeepQuantCloud-${GITHUB_REF#refs/tags/}.zip . -x "*.git*"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            DeepQuantCloud-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 47.239.82.231  # 你的服务器公网IP地址
          username: root  # 你的用户名，登录服务器的时候，登录界面能看见
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22  # 你的SSH端口，一般都是22，可以登录服务器后查出来ssh端口号
          script: |
            cd /var/github/DeepQuantCloud
            git pull origin ${{ github.ref_name }}  # 里边是tag的名
            docker-compose restart web
